import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const base=fileURLToPath(new URL('..',import.meta.url));
const map=new Map();
const key=r=>typeof r==='string'?r:r.url;
const caches={async open(name){if(!map.has(name))map.set(name,new Map());const m=map.get(name);return{async put(r,v){m.set(key(r),v.clone());},async match(r){return m.get(key(r))?.clone();},async addAll(urls){for(const u of urls)m.set(u,new Response('shell'));}};},async keys(){return [...map.keys()];},async delete(n){return map.delete(n);},async match(r){for(const m of map.values()){if(m.has(key(r)))return m.get(key(r)).clone();}}};
const handlers={};let claimed=false,skipped=false;
const self={location:'https://example.com/tiny-signs/sw.js',addEventListener(name,cb){handlers[name]=cb;},async skipWaiting(){skipped=true;},clients:{async claim(){claimed=true;}}};
const code=(await fs.readFile(base+'/scripts/sw-template.js','utf8')).replace('__SHELL_VERSION__','test').replace('__PRECACHE__',JSON.stringify(['index.html','credits.html']));
const context=vm.createContext({self,caches,URL,Response,fetch:async()=>{throw new Error('offline');}});vm.runInContext(code,context);
await new Promise((resolve,reject)=>handlers.install({waitUntil:p=>p.then(resolve,reject)}));assert(skipped);
await caches.open('tiny-signs-shell-old');await caches.open('another-app');
await new Promise((resolve,reject)=>handlers.activate({waitUntil:p=>p.then(resolve,reject)}));assert(claimed);assert(!map.has('tiny-signs-shell-old'));assert(map.has('another-app'));
const media=await caches.open('tiny-signs-media-v1');await media.put('https://example.com/tiny-signs/media/milk.mp4',new Response(Uint8Array.from({length:100},(_,i)=>i),{headers:{'Content-Type':'video/mp4'}}));
async function request(url,range,mode='cors'){let result;handlers.fetch({request:{url,method:'GET',mode,headers:new Headers(range?{range}:undefined)},respondWith:p=>result=p});return result;}
let r=await request('https://example.com/tiny-signs/media/milk.mp4','bytes=10-19');assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),'bytes 10-19/100');assert.equal((await r.arrayBuffer()).byteLength,10);
r=await request('https://example.com/tiny-signs/media/milk.mp4','bytes=-7');assert.equal(r.headers.get('Content-Range'),'bytes 93-99/100');
r=await request('https://example.com/tiny-signs/media/milk.mp4','bytes=200-');assert.equal(r.status,416);
r=await request('https://example.com/tiny-signs/','', 'navigate');assert.equal(await r.text(),'shell');assert.equal(await request('https://example.com/other/'),undefined);
const req=createRequire(base+'/package.json');const {createServer}=await import(req.resolve('vite'));const vite=await createServer({root:base,server:{middlewareMode:true},appType:'custom'});
globalThis.window={location:{origin:'https://example.com'},caches};Object.defineProperty(globalThis,'navigator',{value:{serviceWorker:{}},configurable:true});globalThis.caches=caches;
let fetched=0;globalThis.fetch=async()=>{fetched++;return new Response('media',{status:200});};
const pack=await vite.ssrLoadModule('/src/offline.js');await pack.removeOfflinePack();let state=await pack.offlineStatus();assert.equal(state.count,0);
let progress=0;state=await pack.saveOfflinePack(n=>progress=n,new AbortController().signal);assert.equal(state.count,60);assert.equal(progress,60);assert.equal(fetched,60);
await pack.saveOfflinePack(()=>{},new AbortController().signal);assert.equal(fetched,60,'reuse downloaded files');await pack.removeOfflinePack();assert.equal((await pack.offlineStatus()).count,0);
const abort=new AbortController();abort.abort();await assert.rejects(()=>pack.saveOfflinePack(()=>{},abort.signal));
await vite.close();console.log('PASS: offline installation, scoped cache cleanup, offline navigation, full and partial video ranges, invalid ranges, 60-file pack download, status, reuse, removal and cancellation.');process.exit(0);
